// Package testing provides test output parsing and analysis.
package testing

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"regexp"
	"strconv"
	"strings"
)

// TestEvent represents a single event from go test -json output.
type TestEvent struct {
	Elapsed float64 `json:"Elapsed"`
	Time    string  `json:"Time"`
	Action  string  `json:"Action"` // run, pass, fail, skip, output, bench
	Package string  `json:"Package"`
	Test    string  `json:"Test"`
	Output  string  `json:"Output"`
}

// TestFailure represents a test failure with details extracted from output.
type TestFailure struct {
	Duration  float64 // 8 bytes
	Line      int     // 8 bytes
	Output    []string
	Package   string
	Test      string
	File      string
	Timestamp string
	FullName  string // Package/Test combined
}

// ParseTestJSON parses go test -json output and returns all test failures.
// The input reader should contain newline-delimited JSON events.
func ParseTestJSON(r io.Reader) ([]*TestFailure, error) {
	scanner := bufio.NewScanner(r)
	failures := make([]*TestFailure, 0)
	runningTests := make(map[string]*TestFailure)

	for scanner.Scan() {
		var event TestEvent
		if err := json.Unmarshal(scanner.Bytes(), &event); err != nil {
			// Skip malformed lines
			continue
		}

		switch event.Action {
		case "fail":
			key := event.Package + "/" + event.Test
			if f, exists := runningTests[key]; exists {
				// Update existing test record
				f.Duration = event.Elapsed
				f.Timestamp = event.Time
				failures = append(failures, f)
				delete(runningTests, key)
			} else {
				// Create new failure record
				f := &TestFailure{
					Package:   event.Package,
					Test:      event.Test,
					FullName:  key,
					Duration:  event.Elapsed,
					Timestamp: event.Time,
					Output:    make([]string, 0),
				}
				failures = append(failures, f)
			}

		case "output":
			if event.Test != "" {
				key := event.Package + "/" + event.Test
				if _, exists := runningTests[key]; !exists {
					runningTests[key] = &TestFailure{
						Package:  event.Package,
						Test:     event.Test,
						FullName: key,
						Output:   make([]string, 0),
					}
				}
				runningTests[key].Output = append(runningTests[key].Output, event.Output)

				// Extract file:line information from output
				if strings.Contains(event.Output, ".go:") {
					if file, line, ok := extractFileLocation(event.Output); ok {
						runningTests[key].File = file
						runningTests[key].Line = line
					}
				}
			}
		}
	}

	return failures, scanner.Err()
}

// extractFileLocation attempts to extract file and line number from test output.
// Matches patterns like: "path/to/file.go:123:" or "file.go:45:"
func extractFileLocation(output string) (string, int, bool) {
	// Match patterns like: file.go:123: or /path/to/file.go:456:
	re := regexp.MustCompile(`([\w./\-]+\.go):(\d+):`)
	matches := re.FindStringSubmatch(output)
	if len(matches) >= 3 {
		file := matches[1]
		lineNum, err := strconv.Atoi(matches[2])
		if err == nil {
			return file, lineNum, true
		}
	}
	return "", 0, false
}

// FormatIssueBody creates a markdown-formatted issue body from test failure.
// Returns a string suitable for use as GitHub issue body.
func (f *TestFailure) FormatIssueBody() string {
	var sb strings.Builder

	sb.WriteString("## Test Failure\n\n")

	// Summary section
	sb.WriteString("**Package:** `" + f.Package + "`\n")
	sb.WriteString("**Test:** `" + f.Test + "`\n")
	if f.Duration > 0 {
		sb.WriteString(fmt.Sprintf("**Duration:** %.3fs\n", f.Duration))
	}
	sb.WriteString("**Failed at:** " + f.Timestamp + "\n\n")

	// File location if available
	if f.File != "" {
		sb.WriteString("### Location\n")
		sb.WriteString("`" + f.File)
		if f.Line > 0 {
			sb.WriteString(fmt.Sprintf(":%d", f.Line))
		}
		sb.WriteString("`\n\n")
	}

	// Error output
	if len(f.Output) > 0 {
		sb.WriteString("### Error Output\n```\n")
		for _, line := range f.Output {
			sb.WriteString(line)
		}
		sb.WriteString("```\n\n")
	}

	// Footer
	sb.WriteString("---\n_Auto-generated by bc testing demon_\n")

	return sb.String()
}

// IssueTitle generates a concise issue title from the test failure.
// Returns a title like "[Test Failure] TestFunctionName - package"
func (f *TestFailure) IssueTitle() string {
	testName := f.Test
	if testName == "" {
		testName = "package test"
	}
	return fmt.Sprintf("[Test Failure] %s - %s", testName, packageShortName(f.Package))
}

// packageShortName extracts the last component of a package path.
// Example: "github.com/user/repo/pkg/agent" -> "agent"
func packageShortName(pkg string) string {
	parts := strings.Split(pkg, "/")
	if len(parts) > 0 && parts[len(parts)-1] != "" {
		return parts[len(parts)-1]
	}
	return pkg
}
