package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/spf13/cobra"

	"github.com/rpuneet/bc/pkg/log"
)

var issueCmd = &cobra.Command{
	Use:   "issue",
	Short: "Manage GitHub issues",
	Long: `Manage GitHub issues from test results.

The issue command provides automated issue creation from test failures.

Examples:
  bc issue create --type bug --title "Test failure"    # Create bug issue
  bc issue create --type enhancement --title "Improve" # Create enhancement
  bc issue list --labels bug,test-failure              # List issues`,
}

var issueCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a GitHub issue",
	Long: `Create a GitHub issue with specified type and details.

Examples:
  bc issue create --type bug --title "Test failure: agent timeout"
  bc issue create --type enhancement --title "Add retry logic"`,
	RunE: runIssueCreate,
}

var issueListCmd = &cobra.Command{
	Use:   "list",
	Short: "List GitHub issues",
	Long: `List GitHub issues with optional filters.

Examples:
  bc issue list                        # List all open issues
  bc issue list --labels test-failure  # List by label`,
	RunE: runIssueList,
}

var (
	issueType        string
	issueTitle       string
	issueDescription string
	issueLabels      string
	issueSeverity    string
	issueReproSteps  string
)

func init() {
	// issue create flags
	issueCreateCmd.Flags().StringVar(&issueType, "type", "bug", "Issue type (bug, enhancement, test-failure)")
	issueCreateCmd.Flags().StringVar(&issueTitle, "title", "", "Issue title")
	issueCreateCmd.Flags().StringVar(&issueDescription, "description", "", "Issue description")
	issueCreateCmd.Flags().StringVar(&issueLabels, "labels", "", "Comma-separated labels")
	issueCreateCmd.Flags().StringVar(&issueSeverity, "severity", "medium", "Severity (critical, high, medium, low)")
	issueCreateCmd.Flags().StringVar(&issueReproSteps, "reproduction", "", "Reproduction steps")

	// issue list flags
	issueListCmd.Flags().StringVar(&issueLabels, "labels", "", "Filter by labels")

	// Add subcommands
	issueCmd.AddCommand(issueCreateCmd)
	issueCmd.AddCommand(issueListCmd)

	rootCmd.AddCommand(issueCmd)
}

// IssueData represents GitHub issue creation data
type IssueData struct {
	Title       string   `json:"title"`
	Body        string   `json:"body"`
	Type        string   `json:"type"`
	Severity    string   `json:"severity"`
	TestFailure string   `json:"test_failure,omitempty"`
	Labels      []string `json:"labels,omitempty"`
}

// CreateIssueFromTestFailure creates a GitHub issue from a test failure
func CreateIssueFromTestFailure(testName, output, reproduction string) (*IssueData, error) {
	title := fmt.Sprintf("Test failure: %s", testName)

	body := fmt.Sprintf(`## Test Failure Report

**Test:** %s

### Reproduction
%s

### Test Output
%s

### Environment
- Generated by: bc test (automated)
- Severity: high

---
🤖 Auto-generated by bc test demons
`, testName, reproduction, "```\n"+output+"\n```")

	labels := []string{"bug", "test-failure", "automated"}

	issue := &IssueData{
		Title:       title,
		Body:        body,
		Labels:      labels,
		Type:        "bug",
		Severity:    "high",
		TestFailure: testName,
	}

	return issue, nil
}

func runIssueCreate(cmd *cobra.Command, args []string) error {
	log.Debug("issue create command started")

	if issueTitle == "" {
		return fmt.Errorf("--title is required")
	}

	// Build issue body
	var bodyParts []string
	// Capitalize first letter of issue type
	typeCapitalized := issueType
	if len(issueType) > 0 {
		typeCapitalized = strings.ToUpper(issueType[:1]) + issueType[1:]
	}
	bodyParts = append(bodyParts, fmt.Sprintf("## %s Issue", typeCapitalized))

	if issueDescription != "" {
		bodyParts = append(bodyParts, fmt.Sprintf("\n### Description\n%s", issueDescription))
	}

	if issueReproSteps != "" {
		bodyParts = append(bodyParts, fmt.Sprintf("\n### Reproduction Steps\n%s", issueReproSteps))
	}

	bodyParts = append(bodyParts, fmt.Sprintf("\n### Severity\n%s", issueSeverity))
	bodyParts = append(bodyParts, "\n---\n🤖 Created by bc issue command")

	body := strings.Join(bodyParts, "\n")

	// Build gh command with preallocated capacity
	ghArgs := make([]string, 0, 8)
	ghArgs = append(ghArgs, "issue", "create", "--title", issueTitle, "--body", body)

	// Add labels
	labels := []string{issueType}
	if issueLabels != "" {
		labels = append(labels, strings.Split(issueLabels, ",")...)
	}
	ghArgs = append(ghArgs, "--label", strings.Join(labels, ","))

	// Execute gh command with context
	ctx := context.Background()
	ghCmd := exec.CommandContext(ctx, "gh", ghArgs...) //nolint:gosec // gh is a trusted command
	ghCmd.Stdout = os.Stdout
	ghCmd.Stderr = os.Stderr

	if err := ghCmd.Run(); err != nil {
		return fmt.Errorf("failed to create issue: %w", err)
	}

	return nil
}

func runIssueList(cmd *cobra.Command, args []string) error {
	log.Debug("issue list command started")

	jsonOutput, _ := cmd.Flags().GetBool("json")

	// Build gh command
	ghArgs := make([]string, 0, 6)
	ghArgs = append(ghArgs, "issue", "list")

	if issueLabels != "" {
		ghArgs = append(ghArgs, "--label", issueLabels)
	}

	if jsonOutput {
		ghArgs = append(ghArgs, "--json", "number,title,labels,state,createdAt")
	}

	// Execute gh command with context
	ctx := context.Background()
	ghCmd := exec.CommandContext(ctx, "gh", ghArgs...) //nolint:gosec // gh is a trusted command

	var out bytes.Buffer
	ghCmd.Stdout = &out
	ghCmd.Stderr = os.Stderr

	if err := ghCmd.Run(); err != nil {
		return fmt.Errorf("failed to list issues: %w", err)
	}

	if jsonOutput {
		// Pretty print JSON
		var data interface{}
		if err := json.Unmarshal(out.Bytes(), &data); err != nil {
			fmt.Print(out.String())
			return nil
		}
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}

	fmt.Print(out.String())
	return nil
}
