// Code generated by cfgx. DO NOT EDIT.

package config

type DatabaseConfig struct {
	Driver       string
	MaxIdleConns int64
	MaxOpenConns int64
	Url          string
}

type LogsConfig struct {
	MaxBytes     int64
	Path         string
	PreserveAnsi bool
}

type PerformanceConfig struct {
	AdaptiveFastInterval   int64
	AdaptiveMaxInterval    int64
	AdaptiveNormalInterval int64
	AdaptiveSlowInterval   int64
	CacheTtlCommands       int64
	CacheTtlTmux           int64
	PollIntervalAgents     int64
	PollIntervalChannels   int64
	PollIntervalCosts      int64
	PollIntervalDemons     int64
	PollIntervalLogs       int64
	PollIntervalStatus     int64
	PollIntervalTeams      int64
}

type ProvidersAiderConfig struct {
	Command string
	Enabled bool
}

type ProvidersClaudeConfig struct {
	Command string
	Enabled bool
}

type ProvidersCodexConfig struct {
	Command string
	Enabled bool
}

type ProvidersConfig struct {
	Aider    ProvidersAiderConfig
	Claude   ProvidersClaudeConfig
	Codex    ProvidersCodexConfig
	Cursor   ProvidersCursorConfig
	Default  string
	Gemini   ProvidersGeminiConfig
	Openclaw ProvidersOpenclawConfig
	Opencode ProvidersOpencodeConfig
}

type ProvidersCursorConfig struct {
	Command string
	Enabled bool
}

type ProvidersGeminiConfig struct {
	Command string
	Enabled bool
}

type ProvidersOpenclawConfig struct {
	Command string
	Enabled bool
}

type ProvidersOpencodeConfig struct {
	Command string
	Enabled bool
}

type RuntimeConfig struct {
	Backend string
	Docker  RuntimeDockerConfig
}

type RuntimeDockerConfig struct {
	Cpus     float64
	Image    string
	MemoryMb int64
	Network  string
}

type ServicesConfig struct {
	Github ServicesGithubConfig
	Gitlab ServicesGitlabConfig
	Jira   ServicesJiraConfig
}

type ServicesGithubConfig struct {
	Command string
	Enabled bool
}

type ServicesGitlabConfig struct {
	Command string
	Enabled bool
}

type ServicesJiraConfig struct {
	Command string
	Enabled bool
}

type TmuxConfig struct {
	SessionPrefix string
}

type TuiConfig struct {
	LeaderBindings     TuiLeaderBindingsConfig
	LeaderKey          string
	ScrollAcceleration bool
	ScrollSpeed        int64
	Theme              string
}

type TuiLeaderBindingsConfig struct {
	H string
	N string
	Q string
	S string
	T string
	X string
}

type WorkspaceConfig struct {
	Name    string
	Path    string
	Version int64
}

var (
	Database = DatabaseConfig{
		Driver:       "sqlite",
		MaxIdleConns: 5,
		MaxOpenConns: 10,
		Url:          "",
	}
	Logs = LogsConfig{
		MaxBytes:     1048576,
		Path:         ".bc/logs",
		PreserveAnsi: true,
	}
	Performance = PerformanceConfig{
		AdaptiveFastInterval:   1000,
		AdaptiveMaxInterval:    8000,
		AdaptiveNormalInterval: 2000,
		AdaptiveSlowInterval:   4000,
		CacheTtlCommands:       5000,
		CacheTtlTmux:           2000,
		PollIntervalAgents:     2000,
		PollIntervalChannels:   3000,
		PollIntervalCosts:      5000,
		PollIntervalDemons:     5000,
		PollIntervalLogs:       3000,
		PollIntervalStatus:     2000,
		PollIntervalTeams:      10000,
	}
	Providers = ProvidersConfig{
		Aider: ProvidersAiderConfig{
			Command: "aider --yes",
			Enabled: false,
		},
		Claude: ProvidersClaudeConfig{
			Command: "claude",
			Enabled: true,
		},
		Codex: ProvidersCodexConfig{
			Command: "codex --full-auto",
			Enabled: false,
		},
		Cursor: ProvidersCursorConfig{
			Command: "cursor-agent --force --print",
			Enabled: false,
		},
		Default: "claude",
		Gemini: ProvidersGeminiConfig{
			Command: "gemini --yolo",
			Enabled: true,
		},
		Openclaw: ProvidersOpenclawConfig{
			Command: "openclaw --auto",
			Enabled: false,
		},
		Opencode: ProvidersOpencodeConfig{
			Command: "crush",
			Enabled: false,
		},
	}
	Runtime = RuntimeConfig{
		Backend: "docker",
		Docker: RuntimeDockerConfig{
			Cpus:     2,
			Image:    "bc-agent:latest",
			MemoryMb: 2048,
			Network:  "bridge",
		},
	}
	Services = ServicesConfig{
		Github: ServicesGithubConfig{
			Command: "gh",
			Enabled: false,
		},
		Gitlab: ServicesGitlabConfig{
			Command: "glab",
			Enabled: false,
		},
		Jira: ServicesJiraConfig{
			Command: "jira",
			Enabled: false,
		},
	}
	Tmux = TmuxConfig{
		SessionPrefix: "bc-",
	}
	Tui = TuiConfig{
		LeaderBindings: TuiLeaderBindingsConfig{
			H: "help",
			N: "new_session",
			Q: "quit",
			S: "sessions",
			T: "themes",
			X: "export",
		},
		LeaderKey:          "ctrl+x",
		ScrollAcceleration: false,
		ScrollSpeed:        3,
		Theme:              "auto",
	}
	Workspace = WorkspaceConfig{
		Name:    "bc",
		Path:    "",
		Version: 2,
	}
)
