// Code generated by cfgx. DO NOT EDIT.

package config

type AgentLegacyConfig struct {
	Command string
}

type AgentsItem struct {
	Command     string
	Description string
	Name        string
}

type ChannelsConfig struct {
	Default []string
}

type MemoryConfig struct {
	Backend string
	Path    string
}

type PerformanceConfig struct {
	AdaptiveFastInterval   int64
	AdaptiveMaxInterval    int64
	AdaptiveNormalInterval int64
	AdaptiveSlowInterval   int64
	CacheTtlCommands       int64
	CacheTtlTmux           int64
	PollIntervalAgents     int64
	PollIntervalChannels   int64
	PollIntervalCosts      int64
	PollIntervalDemons     int64
	PollIntervalLogs       int64
	PollIntervalStatus     int64
	PollIntervalTeams      int64
}

type RosterConfig struct {
	Engineers int64
	Qa        int64
	TechLeads int64
}

type TmuxConfig struct {
	SessionPrefix string
}

type ToolsClaudeConfig struct {
	Command string
	Enabled bool
}

type ToolsCodexConfig struct {
	Command string
	Enabled bool
}

type ToolsConfig struct {
	Claude  ToolsClaudeConfig
	Codex   ToolsCodexConfig
	Cursor  ToolsCursorConfig
	Default string
	Gemini  ToolsGeminiConfig
	Github  ToolsGithubConfig
	Gitlab  ToolsGitlabConfig
	Jira    ToolsJiraConfig
}

type ToolsCursorConfig struct {
	Command string
	Enabled bool
}

type ToolsGeminiConfig struct {
	Command string
	Enabled bool
}

type ToolsGithubConfig struct {
	Command string
	Enabled bool
}

type ToolsGitlabConfig struct {
	Command string
	Enabled bool
}

type ToolsJiraConfig struct {
	Command string
	Enabled bool
}

type WorkspaceConfig struct {
	Name    string
	Version int64
}

type WorktreesConfig struct {
	AutoCleanup bool
	Path        string
}

var (
	AgentLegacy = AgentLegacyConfig{
		Command: "claude --dangerously-skip-permissions",
	}
	Agents = []AgentsItem{
		{
			Command:     "claude --dangerously-skip-permissions",
			Description: "Anthropic Claude Code",
			Name:        "claude",
		},
		{
			Command:     "gemini --yolo",
			Description: "Gemini Agent",
			Name:        "gemini",
		},
		{
			Command:     "cursor-agent --force --print",
			Description: "Cursor Agent",
			Name:        "cursor",
		},
		{
			Command:     "codex --full-auto",
			Description: "OpenAI Codex",
			Name:        "codex",
		},
	}
	Channels = ChannelsConfig{
		Default: []string{"general", "engineering"},
	}
	Memory = MemoryConfig{
		Backend: "file",
		Path:    ".bc/memory",
	}
	Performance = PerformanceConfig{
		AdaptiveFastInterval:   1000,
		AdaptiveMaxInterval:    8000,
		AdaptiveNormalInterval: 2000,
		AdaptiveSlowInterval:   4000,
		CacheTtlCommands:       5000,
		CacheTtlTmux:           2000,
		PollIntervalAgents:     2000,
		PollIntervalChannels:   3000,
		PollIntervalCosts:      5000,
		PollIntervalDemons:     5000,
		PollIntervalLogs:       3000,
		PollIntervalStatus:     2000,
		PollIntervalTeams:      10000,
	}
	Roster = RosterConfig{
		Engineers: 4,
		Qa:        2,
		TechLeads: 2,
	}
	Tmux = TmuxConfig{
		SessionPrefix: "bc-",
	}
	Tools = ToolsConfig{
		Claude: ToolsClaudeConfig{
			Command: "claude --dangerously-skip-permissions",
			Enabled: true,
		},
		Codex: ToolsCodexConfig{
			Command: "codex --full-auto",
			Enabled: false,
		},
		Cursor: ToolsCursorConfig{
			Command: "cursor-agent --force --print",
			Enabled: false,
		},
		Default: "claude",
		Gemini: ToolsGeminiConfig{
			Command: "gemini --yolo",
			Enabled: true,
		},
		Github: ToolsGithubConfig{
			Command: "gh",
			Enabled: false,
		},
		Gitlab: ToolsGitlabConfig{
			Command: "glab",
			Enabled: false,
		},
		Jira: ToolsJiraConfig{
			Command: "jira",
			Enabled: false,
		},
	}
	Workspace = WorkspaceConfig{
		Name:    "bc",
		Version: 2,
	}
	Worktrees = WorktreesConfig{
		AutoCleanup: true,
		Path:        ".bc/worktrees",
	}
)
